server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ksc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: winhulin
logging:
  level:
    com:
      rum:
        ksc_back:
          com.rum.ksc_back.KscBackApplication: debug
mybatis:
  mapper-locations: classpath:Dao/*Mapper.xml
  type-aliases-package: com.rum.ksc_back.domain.Ron
